### PR TITLE
added class for get file system statistics.

### PR DESCRIPTION
**Pull request by doronzuk**
added class to support request for DescribeFileSystemStatistics.
this is supported in openAPI but is not implemented in any of the SDKs

### CODE REVIEW

**Comment by doronzuk** [comment]
@samuelchen, @suzaku  can you please take a look, only missing 2 reviewers

**Comment by samuelchen** [comment]
OK to me

**Comment by doronzuk** [comment]
@samuelchen , @suzaku so we have 2 reviews? can we merge?

**Comment by JacksonTian** [comment]
The code was auto-generated, next time will overwrite your commits. I will notice the NAS team to update the SDK.

**Pull request closed without merging**
