### PR TITLE
Add GetCallerIdentityRequest module to STS SDK

### LINKED ISSUE #7: sts:GetCallerIdentity not implemented?
There is only `AssumeRoleRequest` in sts SDK, but I did see `GetCallerIdentity` API in [STS API documentation][1]. When will this get implemented in the Python SDK?

[1]: https://help.aliyun.com/document_detail/43767.html

### PR DESCRIPTION
**Pull request by JokerQyou**
As documented [here][1]. This would fix #7 .

[1]: https://help.aliyun.com/document_detail/43767.html

### CODE REVIEW

**Comment by JokerQyou** [comment]
Anyone can take a look at this?

**Comment by Qingtang-SDK** [comment]
@JokerQyou  Thank you for post this fix, we are looking at this fix now, and reply you as soon as possible. We are very sorry for the late response.

**Comment by gaort** [comment]
@JokerQyou thanks for your contribute and feedback!
I'm very sorry we hasn't complete the CONTRIBUTE.md yet
the codes changed in this PR is auto-generated by a code generator
so we're not recommend to change any code except in the core or core-v3 dir

**Comment by JokerQyou** [comment]
So maybe you could at least commit a `CONTRIBUTE.md` ? I bet many developers would do their own monkey patches instead of contributing to your code, for:

- You have no contributing guide at all;
- You're way too slow at replying issues or PRs; (I mean, just look at the timeline of this PR, it took literally a full year to get the first human reply)

Of course, personally I'm fine with monkey patches, and I understand that updating SDKs on github is probably not part of your full time job.

**Pull request closed without merging**
